# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: GitHub Pages Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  # Building job
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.5.1']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
          export OAUTH_CLIENT_ID=${{secrets.OAUTH_CLIENT_ID}}
    - run: npm ci
    - run: npm run build
    
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
  
